In [1]:
!pip install torch transformers bitsandbytes accelerate sqlparse

Requirement already satisfied: torch in /opt/conda/lib/python3.10/site-packages (2.1.2)
Requirement already satisfied: transformers in /opt/conda/lib/python3.10/site-packages (4.38.2)
Collecting bitsandbytes
  Downloading bitsandbytes-0.43.0-py3-none-manylinux_2_24_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: accelerate in /opt/conda/lib/python3.10/site-packages (0.28.0)
Requirement already satisfied: sqlparse in /opt/conda/lib/python3.10/site-packages (0.4.4)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torch) (4.9.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch) (2024.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /opt/conda/lib/python3.10/site-packages (from transformers) (0.21.4)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers) (21.3)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers) (2023.12.25)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /opt/conda/lib/python3.10/site-packages (from transformers) (0.15.2)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers) (0.4.2)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers) (4.66.1)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate) (5.9.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging>=20.0->transformers) (3.1.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (2024.2.2)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch) (1.3.0)
Downloading bitsandbytes-0.43.0-py3-none-manylinux_2_24_x86_64.whl (102.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.2/102.2 MB 15.2 MB/s eta 0:00:0000:0100:01
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.43.0

In [2]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

In [3]:
torch.cuda.is_available()

True

In [4]:
available_memory = torch.cuda.get_device_properties(0).total_memory

In [5]:
print(available_memory)

17066885120

In [6]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"

In [7]:

# Cloning the GitHub repository
!git clone -q https://github.com/glee4810/ehrsql-2024.git
%cd ehrsql-2024

/kaggle/working/ehrsql-2024

In [8]:
import os
import json
import pandas as pd

# Directory paths for database, results and scoring program
DB_ID = 'mimic_iv'
BASE_DATA_DIR = 'data/mimic_iv'
RESULT_DIR = 'sample_result_submission/'
SCORE_PROGRAM_DIR = 'scoring_program/'

# File paths for the dataset and labels
TABLES_PATH = os.path.join('data', DB_ID, 'tables.json')               # JSON containing database schema
TRAIN_DATA_PATH = os.path.join(BASE_DATA_DIR, 'train', 'data.json')    # JSON file with natural language questions for training data
TRAIN_LABEL_PATH = os.path.join(BASE_DATA_DIR, 'train', 'label.json')  # JSON file with corresponding SQL queries for training data
VALID_DATA_PATH = os.path.join(BASE_DATA_DIR, 'test', 'data.json')    # JSON file for validation data
DB_PATH = os.path.join('data', DB_ID, f'{DB_ID}.sqlite')               # Database path

In [9]:
!wget https://physionet.org/static/published-projects/mimic-iv-demo/mimic-iv-clinical-database-demo-2.2.zip
!unzip mimic-iv-clinical-database-demo-2.2
!gunzip -r mimic-iv-clinical-database-demo-2.2

--2024-03-26 07:22:18--  https://physionet.org/static/published-projects/mimic-iv-demo/mimic-iv-clinical-database-demo-2.2.zip
Resolving physionet.org (physionet.org)... 18.18.42.54
Connecting to physionet.org (physionet.org)|18.18.42.54|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16189661 (15M) [application/zip]
Saving to: 'mimic-iv-clinical-database-demo-2.2.zip'

mimic-iv-clinical-d 100%[===================>]  15.44M   154KB/s    in 80s

2024-03-26 07:23:39 (198 KB/s) - 'mimic-iv-clinical-database-demo-2.2.zip' saved [16189661/16189661]

Archive:  mimic-iv-clinical-database-demo-2.2.zip
  inflating: mimic-iv-clinical-database-demo-2.2/LICENSE.txt
  inflating: mimic-iv-clinical-database-demo-2.2/README.txt
  inflating: mimic-iv-clinical-database-demo-2.2/SHA256SUMS.txt
  inflating: mimic-iv-clinical-database-demo-2.2/demo_subject_id.csv
 extracting: mimic-iv-clinical-database-demo-2.2/hosp/admissions.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/d_hcpcs.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/d_icd_diagnoses.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/d_icd_procedures.csv.gz
 extracting: mimic-iv-clinical-database-demo-2.2/hosp/d_labitems.csv.gz
 extracting: mimic-iv-clinical-database-demo-2.2/hosp/diagnoses_icd.csv.gz
 extracting: mimic-iv-clinical-database-demo-2.2/hosp/drgcodes.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/emar.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/emar_detail.csv.gz
 extracting: mimic-iv-clinical-database-demo-2.2/hosp/hcpcsevents.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/labevents.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/microbiologyevents.csv.gz
 extracting: mimic-iv-clinical-database-demo-2.2/hosp/omr.csv.gz
 extracting: mimic-iv-clinical-database-demo-2.2/hosp/patients.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/pharmacy.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/poe.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/poe_detail.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/prescriptions.csv.gz
 extracting: mimic-iv-clinical-database-demo-2.2/hosp/procedures_icd.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/hosp/provider.csv.gz
 extracting: mimic-iv-clinical-database-demo-2.2/hosp/services.csv.gz
 extracting: mimic-iv-clinical-database-demo-2.2/hosp/transfers.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/icu/caregiver.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/icu/chartevents.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/icu/d_items.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/icu/datetimeevents.csv.gz
 extracting: mimic-iv-clinical-database-demo-2.2/icu/icustays.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/icu/ingredientevents.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/icu/inputevents.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/icu/outputevents.csv.gz
  inflating: mimic-iv-clinical-database-demo-2.2/icu/procedureevents.csv.gz

In [10]:
%cd preprocess
!bash preprocess.sh
%cd ..

/kaggle/working/ehrsql-2024/preprocess
timeshift is True
start_year: 2100
time_span: 0
current_time: 2100-12-31 23:59:00
Processing patients, admissions, icustays, transfers
Cannot take a larger sample than population when 'replace=False
Use all available patients instead.
num_cur_patient: 4
num_non_cur_patient: 90
num_patient: 94
patients, admissions, icustays, transfers processed (took 0.2297 secs)
Processing dictionary tables (d_icd_diagnoses, d_icd_procedures, d_labitems, d_items)
d_icd_diagnoses, d_icd_procedures, d_labitems, d_items processed (took 2.5758 secs)
Processing diagnoses_icd table
diagnoses_icd processed (took 0.1616 secs)
Processing procedures_icd table
procedures_icd processed (took 0.0604 secs)
Processing labevents table
labevents processed (took 2.7756 secs)
Processing prescriptions table
prescriptions processed (took 0.8669 secs)
Processing COST table
cost processed (took 0.6457 secs)
Processing chartevents table
chartevents processed (took 4.2733 secs)
Processing inputevents table
inputevents processed (took 0.6459 secs)
Processing outputevents table
outputevents processed (took 0.4442 secs)
Processing microbiologyevents table
microbiologyevents processed (took 0.1113 secs)
0               patients
1             admissions
2        d_icd_diagnoses
3       d_icd_procedures
4             d_labitems
5                d_items
6          diagnoses_icd
7         procedures_icd
8              labevents
9          prescriptions
10                  cost
11           chartevents
12           inputevents
13          outputevents
14    microbiologyevents
15              icustays
16             transfers
Name: name, dtype: object
Done!

/kaggle/working/ehrsql-2024

In [11]:
from utils.data_io import read_json as read_data

train_data = read_data(TRAIN_DATA_PATH)
train_label = read_data(TRAIN_LABEL_PATH)

valid_data = read_data(VALID_DATA_PATH)

In [12]:
print("Train data:", (len(train_data['data']), len(train_label)))
print("Valid data:", len(valid_data['data']))

Train data: (5124, 5124)
Valid data: 1167

In [13]:
# Explore keys and data structure
print(train_data.keys())
print(train_data['version'])
print(train_data['data'][0]['id'])
print(train_data['data'][0]['question'])

# Explore the label structure
# print(train_label.keys())
# print(train_label[list(train_label.keys())[0]])

dict_keys(['version', 'data'])
mimic_iv_demo_1.0_train
3b9849548e56c59f768d5447
Tell me the minimum respiratory rate in patient 10021118 in the first ICU visit.

Model Building Starts

In [14]:
!pip install accelerate

Requirement already satisfied: accelerate in /opt/conda/lib/python3.10/site-packages (0.28.0)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from accelerate) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from accelerate) (21.3)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate) (5.9.3)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.10/site-packages (from accelerate) (6.0.1)
Requirement already satisfied: torch>=1.10.0 in /opt/conda/lib/python3.10/site-packages (from accelerate) (2.1.2)
Requirement already satisfied: huggingface-hub in /opt/conda/lib/python3.10/site-packages (from accelerate) (0.21.4)
Requirement already satisfied: safetensors>=0.3.1 in /opt/conda/lib/python3.10/site-packages (from accelerate) (0.4.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging>=20.0->accelerate) (3.1.1)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.13.1)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (4.9.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.1.2)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (2024.3.0)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from huggingface-hub->accelerate) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub->accelerate) (4.66.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch>=1.10.0->accelerate) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub->accelerate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub->accelerate) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub->accelerate) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub->accelerate) (2024.2.2)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch>=1.10.0->accelerate) (1.3.0)

In [15]:
model_name = "defog/sqlcoder-7b-2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
# if available_memory > 17e9:
#     # if you have atleast 16GB of GPU memory, run load the model in float16
#     model = AutoModelForCausalLM.from_pretrained(
#         model_name,
#         trust_remote_code=True,
#         torch_dtype=torch.float16,
#         device_map="auto",
#         use_cache=True,
#     )
# else:
    # else, load in 8 bits – this is a bit slower
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    trust_remote_code=True,
    # torch_dtype=torch.float16,
    load_in_4bit=True,
    device_map="auto",
    use_cache=True,
)

tokenizer_config.json:   0%|          | 0.00/1.84k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/515 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/691 [00:00<?, ?B/s]

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/3.59G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [16]:
prompt = """### Task
Generate a SQL query to answer [QUESTION]{question}[/QUESTION]

### Instructions
- If you cannot answer the question with the available database schema, return 'Humne kiya'
- Remember that revenue is price multiplied by quantity
- Remember that cost is supply_price multiplied by quantity

### Database Schema
This query will run on a database whose schema is represented in this string:

DROP TABLE IF EXISTS patients;
CREATE TABLE patients 
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL UNIQUE,
    gender VARCHAR(5) NOT NULL,
    dob TIMESTAMP(0) NOT NULL,
    dod TIMESTAMP(0)
);

DROP TABLE IF EXISTS admissions;
CREATE TABLE admissions
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL UNIQUE,
    admittime TIMESTAMP(0) NOT NULL,
    dischtime TIMESTAMP(0),
    admission_type VARCHAR(50) NOT NULL,
    admission_location VARCHAR(50) NOT NULL,
    discharge_location VARCHAR(50),
    insurance VARCHAR(255) NOT NULL,
    language VARCHAR(10),
    marital_status VARCHAR(50),
    age INT NOT NULL,
    FOREIGN KEY(subject_id) REFERENCES patients(subject_id)
);

DROP TABLE IF EXISTS d_icd_diagnoses;
CREATE TABLE d_icd_diagnoses
(
    row_id INT NOT NULL PRIMARY KEY,
    icd_code VARCHAR(10) NOT NULL UNIQUE,
    long_title VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS d_icd_procedures;
CREATE TABLE d_icd_procedures 
(
    row_id INT NOT NULL PRIMARY KEY,
    icd_code VARCHAR(10) NOT NULL UNIQUE,
    long_title VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS d_labitems;
CREATE TABLE d_labitems 
(
    row_id INT NOT NULL PRIMARY KEY,
    itemid INT NOT NULL UNIQUE,
    label VARCHAR(200)
);

DROP TABLE IF EXISTS d_items;
CREATE TABLE d_items 
(
    row_id INT NOT NULL PRIMARY KEY,
    itemid INT NOT NULL UNIQUE,
    label VARCHAR(200) NOT NULL,
    abbreviation VARCHAR(200) NOT NULL,
    linksto VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS diagnoses_icd;
CREATE TABLE diagnoses_icd
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL,
    icd_code VARCHAR(10) NOT NULL,
    charttime TIMESTAMP(0) NOT NULL,
    FOREIGN KEY(hadm_id) REFERENCES admissions(hadm_id),
    FOREIGN KEY(icd_code) REFERENCES d_icd_diagnoses(icd_code)
);

DROP TABLE IF EXISTS procedures_icd;
CREATE TABLE procedures_icd
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL,
    icd_code VARCHAR(10) NOT NULL,
    charttime TIMESTAMP(0) NOT NULL,
    FOREIGN KEY(hadm_id) REFERENCES admissions(hadm_id),
    FOREIGN KEY(icd_code) REFERENCES d_icd_procedures(icd_code)
);

DROP TABLE IF EXISTS labevents;
CREATE TABLE labevents
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL,
    itemid INT NOT NULL,
    charttime TIMESTAMP(0),
    valuenum DOUBLE PRECISION,
    valueuom VARCHAR(20),
    FOREIGN KEY(hadm_id) REFERENCES admissions(hadm_id),
    FOREIGN KEY(itemid) REFERENCES d_labitems(itemid)
);

DROP TABLE IF EXISTS prescriptions;
CREATE TABLE prescriptions
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL,
    starttime TIMESTAMP(0) NOT NULL,
    stoptime TIMESTAMP(0),
    drug VARCHAR(255) NOT NULL,
    dose_val_rx VARCHAR(100) NOT NULL,
    dose_unit_rx VARCHAR(50) NOT NULL,
    route VARCHAR(50) NOT NULL,
    FOREIGN KEY(hadm_id) REFERENCES admissions(hadm_id)
);

DROP TABLE IF EXISTS cost;
CREATE TABLE cost
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    event_id INT NOT NULL,
    chargetime TIMESTAMP(0) NOT NULL,
    cost DOUBLE PRECISION NOT NULL,
    FOREIGN KEY(hadm_id) REFERENCES admissions(hadm_id),
    FOREIGN KEY(event_id) REFERENCES diagnoses_icd(row_id),
    FOREIGN KEY(event_id) REFERENCES procedures_icd(row_id),
    FOREIGN KEY(event_id) REFERENCES labevents(row_id),
    FOREIGN KEY(event_id) REFERENCES prescriptions(row_id)  
);

DROP TABLE IF EXISTS chartevents;
CREATE TABLE chartevents
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL,
    stay_id INT NOT NULL,
    itemid INT NOT NULL,
    charttime TIMESTAMP(0) NOT NULL,
    valuenum DOUBLE PRECISION,
    valueuom VARCHAR(50),
    FOREIGN KEY(hadm_id) REFERENCES admissions(hadm_id),
    FOREIGN KEY(stay_id) REFERENCES icustays(stay_id),
    FOREIGN KEY(itemid) REFERENCES d_items(itemid)
);

DROP TABLE IF EXISTS inputevents;
CREATE TABLE inputevents
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL,
    stay_id INT NOT NULL,
    starttime TIMESTAMP(0) NOT NULL,
    itemid INT NOT NULL,
    amount DOUBLE PRECISION,
    FOREIGN KEY(hadm_id) REFERENCES admissions(hadm_id),
    FOREIGN KEY(stay_id) REFERENCES icustays(stay_id),
    FOREIGN KEY(itemid) REFERENCES d_items(itemid)
);

DROP TABLE IF EXISTS outputevents;
CREATE TABLE outputevents
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL,
    stay_id INT NOT NULL,
    charttime TIMESTAMP(0) NOT NULL,
    itemid INT NOT NULL,
    value DOUBLE PRECISION,
    FOREIGN KEY(hadm_id) REFERENCES admissions(hadm_id),
    FOREIGN KEY(stay_id) REFERENCES icustays(stay_id),
    FOREIGN KEY(itemid) REFERENCES d_items(itemid)
);

DROP TABLE IF EXISTS microbiologyevents;
CREATE TABLE microbiologyevents
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL,
    charttime TIMESTAMP(0) NOT NULL,
    spec_type_desc VARCHAR(100),
    test_name VARCHAR(100),
    org_name VARCHAR(100),
    FOREIGN KEY(hadm_id) REFERENCES admissions(hadm_id)
);

DROP TABLE IF EXISTS icustays;
CREATE TABLE icustays
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL,
    stay_id INT NOT NULL UNIQUE,
    first_careunit VARCHAR(20) NOT NULL,
    last_careunit VARCHAR(20) NOT NULL,
    intime TIMESTAMP(0) NOT NULL,
    outtime TIMESTAMP(0),
    FOREIGN KEY(hadm_id) REFERENCES admissions(hadm_id)
);

DROP TABLE IF EXISTS transfers;
CREATE TABLE transfers
(
    row_id INT NOT NULL PRIMARY KEY,
    subject_id INT NOT NULL,
    hadm_id INT NOT NULL,
    transfer_id INT NOT NULL,
    eventtype VARCHAR(20) NOT NULL,
    careunit VARCHAR(20),
    intime TIMESTAMP(0) NOT NULL,
    outtime TIMESTAMP(0),
    FOREIGN KEY(hadm_id) REFERENCES admissions(hadm_id)
);


### Answer
Given the database schema, here is the SQL query that answers [QUESTION]{question}[/QUESTION]
[SQL]
"""

In [17]:
import sqlparse

def generate_query(question):
    updated_prompt = prompt.format(question=question)
    inputs = tokenizer(updated_prompt, return_tensors="pt").to("cuda")
    generated_ids = model.generate(
        **inputs,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.eos_token_id,
        max_new_tokens=400,
        do_sample=False,
        num_beams=1,
    )

    outputs = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)

    torch.cuda.empty_cache()
    torch.cuda.synchronize()
    # empty cache so that you do generate more results w/o memory crashing
    # particularly important on Colab – memory management is much more straightforward
    # when running on an inference service
    return sqlparse.format(outputs[0].split("[SQL]")[-1], reindent=True)

In [18]:
questions=[]
ids = []
length = len(valid_data['data'])
print(length)
for i in range (length):
    questions.append(valid_data['data'][i]['question'])
    ids.append(valid_data['data'][i]['id'])
#questions

1167

In [19]:
sqls = []
i = 0

# Open a text file in write mode
with open("queries.txt", "w") as file:
    file.write('{')
    for question in questions:
        sql = generate_query(question)
        if 'Humne kiya' in sql:
            sql = 'null'
        sql = sql.replace('\n', '')
        sql = sql.replace(';','')
        sqls.append(sql)
        id=ids[i]
        print(id+":",end="")
        # Write the id and SQL query to the file within double quotes
        file.write(f'"{id}":"{sql}",\n')
        
        print(sql)
        i += 1
        print("Count is ", i)
    file.write('}')
    file.close()

/opt/conda/lib/python3.10/site-packages/bitsandbytes/nn/modules.py:391: UserWarning: Input type into Linear4bit is torch.float16, but bnb_4bit_compute_dtype=torch.float32 (default). This will lead to slow inference or training speed.
  warnings.warn('Input type into Linear4bit is torch.float16, but bnb_4bit_compute_dtype=torch.float32 (default). This will lead to slow inference or training speed.')
2024-03-26 07:25:56.953115: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-26 07:25:56.953224: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-26 07:25:57.085603: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

282f008dd8dfb8f4a1dd6999:SELECT m.org_nameFROM microbiologyevents mJOIN  (SELECT s.subject_id,          MIN(m.charttime) AS min_charttime   FROM microbiologyevents m   JOIN admissions s ON m.hadm_id = s.hadm_id   WHERE s.subject_id = 10027602   GROUP BY s.subject_id) AS min_chart ON m.hadm_id = min_chart.subject_idWHERE m.test_name = 'Urine test'  AND m.spec_type_desc = 'Microorganism'
Count is  1
47fd000ef0b1033a8aabfac8:SELECT p.drug,       COUNT(*) AS frequencyFROM prescriptions pWHERE EXTRACT(YEAR              FROM p.starttime) >= 2010GROUP BY p.drugORDER BY frequency DESCLIMIT 5
Count is  2
7f07c59357750ac2b84e5221:SELECT m.spec_type_desc,       COUNT(*) AS frequencyFROM microbiologyevents mJOIN  (SELECT subject_id   FROM admissions   WHERE charttime >= (CURRENT_DATE - interval '2 months')     AND (icd_code = '757072'          OR icd_code = '757073')   GROUP BY subject_id) AS p ON m.subject_id = p.subject_idGROUP BY m.spec_type_descORDER BY frequency DESCLIMIT 5
Count is  3
c83990de3e5d2d218c83528a:null
Count is  4
f430a02bd152c617a86cd2c3:null
Count is  5
34e18d3b9b2f055f37a2d04d:null
Count is  6
dfc058cc8e8d30a29c0177b9:SELECT COUNT(DISTINCT(p.subject_id)) AS patient_countFROM patients pJOIN diagnoses_icd d ON p.subject_id = d.subject_idJOIN admissions a ON p.subject_id = a.subject_idWHERE d.icd_code = 'thrombocytopenia, unspecified'  AND a.hadm_id IN    (SELECT hadm_id     FROM diagnoses_icd     WHERE icd_code = 'chronic airway obstruction, not elsewhere classified')
Count is  7
4b10d0fec2f23acab915e3f3:SELECT COUNT(*)FROM  (SELECT DISTINCT(p.subject_id) AS patient_id   FROM patients p   JOIN admissions a ON p.subject_id = a.subject_id   JOIN procedures_icd pi ON a.hadm_id = pi.hadm_id   WHERE p.subject_id = 10004457     AND pi.icd_code = '423235'   LIMIT 2) AS subquery
Count is  8
647bc08d18cac6dbda791c42:SELECT MAX(p.starttime) AS last_prescription_timeFROM prescriptions pWHERE p.subject_id = 10018845  AND p.route = 'sc'  AND EXTRACT(YEAR              FROM p.starttime) = 2010
Count is  9
20c3ddd36c65c44890c3f3e5:SELECT m.test_nameFROM microbiologyevents mWHERE m.subject_id = 10021666  AND m.charttime > '2021-03-01'ORDER BY m.charttime ASCLIMIT 1
Count is  10
5436413908d5e902536630e8:SELECT m.test_nameFROM microbiologyevents mJOIN  (SELECT s.subject_id,          MAX(m.charttime) AS max_charttime   FROM microbiologyevents m   JOIN patients s ON m.subject_id = s.subject_id   WHERE s.subject_id = 10018845     AND EXTRACT(YEAR                 FROM m.charttime) = 2021   GROUP BY s.subject_id) AS p ON m.subject_id = p.subject_idWHERE m.charttime = p.max_charttime
Count is  11
4ea7d91dc5b0b0f4da0cb1c6:SELECT p.drug,       COUNT(*) AS COUNTFROM patients pJOIN prescriptions pr ON p.subject_id = pr.subject_idJOIN admissions a ON p.subject_id = a.subject_idWHERE p.drug ilike '%anemia%'  AND p.age >= 60  AND EXTRACT(YEAR              FROM a.admittime) = 2021GROUP BY p.drugORDER BY COUNT DESCLIMIT 3
Count is  12
4f489c24ce6a5dfb8485d4f0:SELECT h.name AS hospital_name,       h.location AS hospital_locationFROM hospitals h
Count is  13
2675abf72b38410bb4eda4ad:SELECT CAST(COUNT(DISTINCT CASE                               WHEN p.dod IS NOT NULL THEN p.subject_id                           END) AS FLOAT) / NULLIF(COUNT(DISTINCT p.subject_id), 0) AS proportionFROM patients pJOIN diagnoses_icd d ON p.subject_id = d.subject_idWHERE d.icd_code = 'A05.0'
Count is  14
3fc7c5e0ee947f0f155f81ae:SELECT MIN(a.dischtime) AS earliest_dischargeFROM admissions aWHERE a.subject_id = 10004422  AND a.dischtime > '2021-01-01'
Count is  15
647fbc4c18dc9b7300f25187:SELECT  (SELECT MIN(d.charttime)   FROM diagnoses_icd d   WHERE d.subject_id = 10021487     AND d.icd_code LIKE '%%other chronic nonalcoholic liver disease%%') -  (SELECT MIN(a.admittime)   FROM admissions a   WHERE a.subject_id = 10021487     AND a.hadm_id = 757071) AS days_since_first_diagnosis
Count is  16
289be48fc696c588e5a69f9c:SELECT p.row_idFROM patients pJOIN diagnoses_icd d ON p.subject_id = d.subject_idWHERE d.icd_code = 'cataract extraction'
Count is  17
3aa4a932c5d33d1b18e92ccc:null
Count is  18
9e26fb10ef1cbf36ec4e516b:null
Count is  19
eeca589fced0d6ee197e6a2b:SELECT a.languageFROM admissions aWHERE a.marital_status = 'married'  AND a.age < 30
Count is  20
c59a0d9f2769a6133e2d4d28:null
Count is  21
9dae764fbde5e025b480528a:SELECT p.row_id,       p.subject_id,       p.gender,       p.dob,       p.dod,       a.hadm_id,       a.admittime,       a.dischtime,       a.admission_type,       a.admission_location,       a.discharge_location,       a.insurance,       a.language,       a.marital_status,       a.age,       i.first_careunit,       i.last_careunit,       c.cost,       s.supply_price,       s.quantity,       s.revenue,       s.cost_per_unit,       s.procedure_code,       s.drug_code,       s.itemid,       s.label,       s.abbreviation,       s.linkstoFROM patients pJOIN admissions a ON p.subject_id = a.subject_idJOIN icustays i ON a.stay_id = i.stay_idJOIN suppliers s ON s.supplier_id = i.first_careunit
Count is  22
fa7797af0bc8368e7b76a129:SELECT  (SELECT labevents.valuenum   FROM labevents   JOIN admissions ON labevents.hadm_id = admissions.hadm_id   WHERE admissions.subject_id = 10004733     AND EXTRACT(HOUR                 FROM labevents.charttime) = 17     AND EXTRACT(MINUTE                 FROM labevents.charttime) = 0     AND EXTRACT(SECOND                 FROM labevents.charttime) = 0) -  (SELECT labevents.valuenum   FROM labevents   JOIN admissions ON labevents.hadm_id = admissions.hadm_id   WHERE admissions.subject_id = 10004733     AND EXTRACT(HOUR                 FROM labevents.charttime) = 16     AND EXTRACT(MINUTE                 FROM labevents.charttime) = 0     AND EXTRACT(SECOND                 FROM labevents.charttime) = 0) AS respiratory_rate_change
Count is  23
c1ba984738060f77fc1c4445:SELECT COUNT(DISTINCT a.subject_id) AS patient_countFROM admissions aWHERE a.dischtime BETWEEN (CURRENT_DATE - INTERVAL '1 year') AND CURRENT_DATE
Count is  24
82af78058d47f0bdbcc12766:null
Count is  25
14867be12327cc1d5dd7348f:null
Count is  26
d3f0d98539d2e9134a435816:SELECT EXTRACT(epoch               FROM (now() -                       (SELECT MIN(p.starttime)                        FROM prescriptions p                        WHERE p.subject_id = 10021487)))/3600 AS hours_passedFROM prescriptions
Count is  27
61a3d12ba8e762f3b53709cd:SELECT m.test_name,       COUNT(*) AS frequencyFROM microbiologyevents mWHERE EXTRACT(YEAR              FROM m.charttime) >= 2010GROUP BY m.test_nameORDER BY frequency DESCLIMIT 5
Count is  28
7e1f1fb83d613020a144d84d:null
Count is  29
e62aab7f7132343b9c06fb6a:null
Count is  30
21d5909e4b60ccf617b739c8:SELECT d_icd_procedures.long_title,       COUNT(*) AS procedure_countFROM d_icd_proceduresJOIN procedures_icd ON d_icd_procedures.icd_code = procedures_icd.icd_codeJOIN admissions ON procedures_icd.hadm_id = admissions.hadm_idJOIN patients ON admissions.subject_id = patients.subject_idWHERE EXTRACT(YEAR              FROM admissions.admittime) = 2010  AND EXTRACT(MONTH              FROM admissions.admittime) = 1  AND patients.gender = 'M'  AND d_icd_procedures.long_title ILIKE '%right%heart%'GROUP BY d_icd_procedures.long_titleORDER BY procedure_count DESC NULLS LASTLIMIT 4
Count is  31
67269f11d04e63d8d4a6aaf1:SELECT d_icd_procedures.long_title,       COUNT(*) AS procedure_countFROM patientsJOIN admissions ON patients.subject_id = admissions.subject_idJOIN diagnoses_icd ON admissions.hadm_id = diagnoses_icd.hadm_idJOIN procedures_icd ON admissions.hadm_id = procedures_icd.hadm_idJOIN d_icd_procedures ON procedures_icd.icd_code = d_icd_procedures.icd_codeWHERE patients.dod IS NULL  AND EXTRACT(YEAR              FROM admissions.dischtime) != 2021  AND EXTRACT(MONTH              FROM admissions.dischtime) = EXTRACT(MONTH                                                   FROM patients.dod)  AND d_icd_procedures.long_title not ilike '%complication%'  AND d_icd_procedures.long_title not ilike '%type%ii%'  AND d_icd_procedures.long_title not ilike '%unspecified%type%'GROUP BY d_icd_procedures.long_titleORDER BY procedure_count DESCLIMIT 5
Count is  32
0c5a19d98fb21ee7f7415577:SELECT p.drugFROM prescriptions pJOIN admissions a ON p.hadm_id = a.hadm_idWHERE p.subject_id = 10021118  AND a.admittime >= date_trunc('month', CURRENT_DATE)  AND a.surgeon_name ILIKE '%left%internal%mammary%'  AND a.procedure_name ILIKE '%bypass%coronary%artery%'  AND a.procedure_name ILIKE '%open%approach%'ORDER BY p.starttime NULLS LAST
Count is  33
2e40656c79819632933f3d54:SELECT COUNT(DISTINCT p.subject_id)FROM patients pJOIN procedures_icd pi ON p.subject_id = pi.subject_idJOIN d_icd_procedures d ON pi.icd_code = d.icd_codeWHERE d.long_title ilike '%right pleural cavity%drainage%device%percutaneous%approach%'
Count is  34
5459fc4c053a74300114b32b:SELECT p.drug,       COUNT(*) AS COUNTFROM prescriptions pWHERE EXTRACT(YEAR              FROM p.starttime) >= 2010GROUP BY p.drugORDER BY COUNT DESCLIMIT 4
Count is  35
f7f4b0b9f1896ea6f3965250:SELECT COUNT(DISTINCT p.subject_id) AS number_of_patientsFROM patients pJOIN icustays i ON p.subject_id = i.subject_idWHERE i.first_careunit = 'Psychiatry'  AND EXTRACT(YEAR              FROM i.intime) >= 2021
Count is  36
915a29cc5d0d25f775a9230e:SELECT COUNT(DISTINCT p.subject_id) AS num_patientsFROM prescriptions pWHERE p.drug ILIKE '%duloxetine%'  AND p.starttime >= (CURRENT_DATE - INTERVAL '1 year')
Count is  37
f9a4d8f655bc4658ff929dab:SELECT d_icd_procedures.long_title,       COUNT(*) AS procedure_countFROM patientsJOIN admissions ON patients.subject_id = admissions.subject_idJOIN procedures_icd ON admissions.hadm_id = procedures_icd.subject_idJOIN d_icd_procedures ON procedures_icd.icd_code = d_icd_procedures.icd_codeWHERE patients.subject_id IN    (SELECT patients.subject_id     FROM patients     JOIN admissions ON patients.subject_id = admissions.subject_id     JOIN procedures_icd ON admissions.hadm_id = procedures_icd.subject_id     JOIN d_icd_procedures ON procedures_icd.icd_code = d_icd_procedures.icd_code     WHERE d_icd_procedures.long_title ilike '%reposition%left%maxilla%with%external%fixation%device%percutaneous%approach%')GROUP BY d_icd_procedures.long_titleORDER BY procedure_count DESCLIMIT 3
Count is  38
3daae260dfa809a3ad93e5bd:null
Count is  39
a7e5f65ddd31811247f49f56:null
Count is  40
95259eb7cea07ea7f2a5cf48:null
Count is  41
a17ee07e69ba77566438512c:SELECT date_trunc('month', c.charttime) AS MONTH,       COUNT(*) AS total_tests,       COUNT(DISTINCT m.itemid) AS distinct_tests,       SUM(c.cost) AS total_cost,       SUM(c.cost * c.valuenum) AS total_cost_with_quantityFROM cost cJOIN labevents l ON c.event_id = l.row_idJOIN microbiologyevents m ON l.row_id = m.row_idWHERE date_part('year', c.charttime) = date_part('year', CURRENT_DATE)  AND m.spec_type_desc ILIKE '%tremor%'GROUP BY MONTHORDER BY total_tests DESC,         distinct_tests DESC,         total_cost DESC,         total_cost_with_quantity DESCLIMIT 4
Count is  42
104c93f89e19274578bafb8d:SELECT MIN(a.admittime) AS first_admissionFROM patients pJOIN admissions a ON p.subject_id = a.subject_idJOIN procedures_icd pi ON a.hadm_id = pi.subject_idWHERE p.subject_id = 10038999  AND pi.icd_code = '12345'
Count is  43
d9b652601ec09231f9991b24:null
Count is  44
e0e182b93545a2f808a87836:null
Count is  45
69c8cd3610b365b38e9dc8fb:null
Count is  46
271fe9a047e24d8cef13cf91:null
Count is  47
62967c2f2d2b967d2139be99:null
Count is  48
297a1435453b2870054eb81d:null
Count is  49
4a82faf774a9f3614964283f:SELECT o.nameFROM outputevents oJOIN patients p ON o.subject_id = p.subject_idWHERE p.subject_id = 10004720  AND o.charttime >= '2021-12-05'ORDER BY o.charttime DESCLIMIT 1
Count is  50
e4373b254aad4b11af3fda65:null
Count is  51
729c62dcfd9ac11a32a56161:SELECT COUNT(p.drug) > 0 AS has_been_prescribedFROM prescriptions pWHERE p.subject_id = 10015860  AND p.starttime >= (CURRENT_DATE - INTERVAL '1 year')
Count is  52
53eee4b8cfb226d8418ce3fa:SELECT d_icd_procedures.long_titleFROM patientsJOIN admissions ON patients.subject_id = admissions.subject_idJOIN procedures_icd ON admissions.hadm_id = procedures_icd.subject_idJOIN d_icd_procedures ON procedures_icd.icd_code = d_icd_procedures.icd_codeWHERE patients.subject_id = 10007818  AND EXTRACT(YEAR              FROM admissions.dischtime) = EXTRACT(YEAR                                                   FROM CURRENT_DATE)ORDER BY d_icd_procedures.long_title DESCLIMIT 1
Count is  53
1b49fcb3998703d3dd37e81e:SELECT AVG(c.cost) AS average_costFROM cost cJOIN procedures_icd p ON c.event_id = p.row_idWHERE p.long_title ILIKE '%other%incision%of%pleura%'
Count is  54
fd884f642b26768cc1d7cecf:SELECT  (SELECT MAX(s.stay_id)   FROM icustays s   WHERE s.subject_id = 10006053) AS max_stay_id,  (SELECT (s.outtime - s.intime) AS length_of_stay   FROM icustays s   WHERE s.stay_id = max_stay_id) AS length_of_stay
Count is  55
8e96be7df6dd4cc4c1e2a3b4:SELECT MIN(p.weight) AS min_weightFROM patients pJOIN admissions a ON p.subject_id = a.subject_idWHERE p.subject_id = 10031757
Count is  56
85c3e2700b75549e5f889cf1:null
Count is  57
770cb760820f25921dc8ac4a:SELECT SUM(c.cost) AS total_costFROM cost cJOIN d_labitems l ON c.event_id = l.itemidWHERE l.label ILIKE '%thyroxine%t4%'  AND c.event_type = 'lab'
Count is  58
939af21d46d24ad0b2940264:null
Count is  59
a2eafdd2283b9391264166aa:WITH last_systolic AS  (SELECT MAX(labevents.valuenum) AS last_systolic   FROM labevents   JOIN admissions ON labevents.hadm_id = admissions.hadm_id   WHERE admissions.subject_id = 10018423     AND labevents.itemid = 10018423     AND admissions.dischtime IS NOT NULL),     first_systolic AS  (SELECT MIN(labevents.valuenum) AS first_systolic   FROM labevents   JOIN admissions ON labevents.hadm_id = admissions.hadm_id   WHERE admissions.subject_id = 10018423     AND labevents.itemid = 10018423     AND admissions.admittime IS NOT NULL)SELECT (last_systolic.last_systolic - first_systolic.first_systolic) AS change_in_systolicFROM last_systolic,     first_systolic
Count is  60
bc8d116f59e4fd75687ea181:SELECT p.drugFROM prescriptions pWHERE p.subject_id = 10004733  AND p.starttime >= (CURRENT_DATE - INTERVAL '1 day')  AND p.starttime < CURRENT_DATEORDER BY p.starttime NULLS LAST
Count is  61
1d673cb43fa93e2f43969f21:null
Count is  62
376ce2f69b8cda44c3960e60:SELECT d_labitems.label,       COUNT(*) AS COUNTFROM labeventsJOIN d_labitems ON labevents.itemid = d_labitems.itemidGROUP BY d_labitems.labelORDER BY COUNT DESCLIMIT 3
Count is  63
ed31b107608f8a15bae7aa15:null
Count is  64
73e1216fd32c02f0a88adb7b:SELECT COUNT(DISTINCT p.subject_id) AS patient_countFROM patients pJOIN prescriptions pr ON p.subject_id = pr.subject_idJOIN diagnoses_icd d ON p.subject_id = d.subject_idWHERE pr.drug ilike '%metronidazole%'  AND d.icd_code ilike '%urinary%tract%infection%'  AND d.charttime >= (CURRENT_DATE - INTERVAL '1 year')  AND (pr.starttime - d.charttime) <= INTERVAL '2 months'
Count is  65
a0cc19360d682b011b5a7c9e:SELECT SUM(c.cost) AS total_costFROM cost cJOIN admissions a ON c.hadm_id = a.hadm_idWHERE a.subject_id = 10021118  AND EXTRACT(YEAR              FROM c.chargetime) >= 2021
Count is  66
eb20ba71a6257201e3668689:null
Count is  67
916c297dfa63e76557d57bb8:null
Count is  68
c410ac2d5f173d57d86ff06c:null
Count is  69
e134d64a96cc7940427b44cf:null
Count is  70
6862d30d896fae9a1cf25fa5:SELECT MAX(c.cost) AS max_total_costFROM cost cJOIN prescriptions p ON c.event_id = p.row_idWHERE p.drug ILIKE '%fenofibrate%'  AND EXTRACT(YEAR              FROM c.chargetime) >= 2021
Count is  71
24e8b0de7b09f21ab851e0c7:null
Count is  72
8de87b88f6cd77d22fb75b7a:SELECT  (SELECT MAX(a.dischtime)   FROM admissions a   WHERE a.subject_id = 10021487     AND a.dischtime < CURRENT_TIMESTAMP()) -  (SELECT MIN(a.admittime)   FROM admissions a   WHERE a.subject_id = 10021487     AND a.admittime <= CURRENT_TIMESTAMP()) AS hours_since_first_diagnosis
Count is  73
633d7843ff15021b4c6b6ac9:SELECT a.marital_statusFROM admissions aWHERE a.subject_id = 10012853ORDER BY a.dischtime DESCLIMIT 1
Count is  74
b96e8ac58176933b9e0ee2b3:SELECT m.test_name,       COUNT(*) AS COUNTFROM microbiologyevents mJOIN  (SELECT subject_id   FROM diagnoses_icd   WHERE icd_code IN ('unarmed fight',                      'brawl')) AS d ON m.subject_id = d.subject_idWHERE m.charttime >= (CURRENT_DATE - INTERVAL '2 months')GROUP BY m.test_nameORDER BY COUNT DESCLIMIT 5
Count is  75
f6f7ea6d73b8b83013dc2f03:SELECT p.subject_id,       p.hadm_id,       p.icustay_id,       d.dischtime,       p.dischtime - d.dischtime AS lead_time,       pr.procedure_name,       row_number() OVER(PARTITION BY p.subject_id                         ORDER BY p.dischtime - d.dischtime DESC) AS lead_rankFROM patients pJOIN procedures_icd pr ON p.hadm_id = pr.subject_idJOIN admissions d ON p.hadm_id = d.hadm_idWHERE p.hadm_id IN    (SELECT hadm_id     FROM patients     WHERE EXTRACT(YEAR                   FROM dob) = EXTRACT(YEAR                                       FROM CURRENT_DATE)       AND icustay_id IN         (SELECT icustay_id          FROM patients          WHERE EXTRACT(MONTH                        FROM admission_date) = EXTRACT(MONTH                                                       FROM CURRENT_DATE)            AND EXTRACT(YEAR                        FROM admission_date) = EXTRACT(YEAR                                                       FROM CURRENT_DATE)            AND procedure_name = 'percutaneous abdominal drainage'))ORDER BY lead_rank
Count is  76
02641abbf2e5bcb72ad7aedc:SELECT m.test_name,       COUNT(*) AS COUNTFROM microbiologyevents mGROUP BY m.test_nameORDER BY COUNT DESCLIMIT 5
Count is  77
e94fc44f50cb46d93aaa3008:SELECT d_icd_diagnoses.icd_code,       d_icd_diagnoses.long_title,       COUNT(*) AS frequencyFROM d_icd_diagnosesJOIN diagnoses_icd ON d_icd_diagnoses.icd_code = diagnoses_icd.icd_codeWHERE d_icd_diagnoses.icd_code::DATE >= '2021-01-01'GROUP BY d_icd_diagnoses.icd_code,         d_icd_diagnoses.long_titleORDER BY frequency DESCLIMIT 5
Count is  78
86741d2d640a5dbbfa5d1036:SELECT MAX(le.valuenum) AS last_valueFROM labevents leJOIN admissions a ON le.hadm_id = a.hadm_idWHERE a.subject_id = 10010471  AND EXTRACT(MONTH              FROM le.charttime) = 5  AND EXTRACT(YEAR              FROM le.charttime) = EXTRACT(YEAR                                           FROM CURRENT_DATE)
Count is  79
0bef44d46b407af716e48911:SELECT  (SELECT     (SELECT valuenum      FROM labevents      WHERE subject_id = 10018328        AND charttime = '2021-05-15 14:00:00') -     (SELECT valuenum      FROM labevents      WHERE subject_id = 10018328        AND charttime = '2021-05-15 13:00:00')) AS difference
Count is  80
59d98dcbea98f9f9a4f33d08:SELECT MAX(i.charttime) AS last_input_timeFROM inputevents iJOIN patients p ON i.subject_id = p.subject_idWHERE p.subject_id = 10013049  AND i.charttime >= '2021-04-09'
Count is  81
3813f972b07ceee5031bb452:null
Count is  82
aef4b8676c07216d65074512:SELECT CURRENT_DATE - MAX(m.charttime) AS days_passedFROM labevents mJOIN patients p ON m.subject_id = p.subject_idWHERE p.subject_id = 10018081  AND m.itemid IN    (SELECT itemid     FROM d_labitems     WHERE label ilike '%osmolality%urine%laboratory%test%')
Count is  83
89fa29a6a2fb6b1fff321ece:null
Count is  84
6938557cc42ba52caf388bef:SELECT SUM(i.amount) AS total_amountFROM inputevents iJOIN patients p ON i.subject_id = p.subject_idWHERE p.subject_id = 10005909  AND i.starttime >= '2021-02-12'
Count is  85
1876fa0cb08f316f3b279b75:null
Count is  86
7e045377b0d1df894941da65:SELECT p.drugFROM prescriptions pWHERE p.subject_id = 10021312GROUP BY p.drugHAVING COUNT(p.drug) >= 2
Count is  87

In [20]:
# sqls = []
# i=0
# for question in questions:
#     sql = generate_query(question)
#     if 'Humne kiya' in sql:
#       sql = 'null'
#     sqls.append(sql.replace('\n', ''))
#     print(sql)
#     i+=1
#     print("Count is ",i)